//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cezzi.Security.Pgp.Tests {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TestResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TestResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Cezzi.Security.Pgp.Tests.TestResources", typeof(TestResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -----BEGIN PGP PRIVATE KEY BLOCK-----
        ///
        ///lQdGBGGwuccBEACsCCOfx4gSZ3l/ddPtzAodkmOJ6lkVDOu2e2VYEAVNzN2LHah7
        ///bs24/A0wRHr1isPhWco6PBeU3q4XDr/9e8TdLrADZYlNegzFokCMWj2h3GQy09pp
        ///Wg89oAvPnAqfYA+IiXf09w1PqH5PZhr+4OagiPQz0n+wjx1rxNO1jPKf38+wUANW
        ///geJtS4razIr4EjwhDMs5wlKkWnXn7L6RLqTQpSEB1Dd4MgBnib76qOu7QxqqUQC9
        ///sSegpCM+2wm+jWBeLyjIQTNdihXG2ZdjQgjlYPQcnqBPdMneI5Y436BdmhD3AW8y
        ///9yEsPvnhkGCPGe2mQq5mqgaDykv/yvSEv7IstHJSP6zkWPN4B6kEKMGYAk+wFcv1
        ///sKhzxeBzbNOoXPbp9ePBZQMXLw2Zf6uFFIUSLnA2pcRnQKobrkFvU3vc9qLbzc+u
        ///mfQwyyCwz [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string private_pgp_key {
            get {
                return ResourceManager.GetString("private_pgp_key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -----BEGIN PGP PUBLIC KEY BLOCK-----
        ///
        ///mQINBGGwuccBEACsCCOfx4gSZ3l/ddPtzAodkmOJ6lkVDOu2e2VYEAVNzN2LHah7
        ///bs24/A0wRHr1isPhWco6PBeU3q4XDr/9e8TdLrADZYlNegzFokCMWj2h3GQy09pp
        ///Wg89oAvPnAqfYA+IiXf09w1PqH5PZhr+4OagiPQz0n+wjx1rxNO1jPKf38+wUANW
        ///geJtS4razIr4EjwhDMs5wlKkWnXn7L6RLqTQpSEB1Dd4MgBnib76qOu7QxqqUQC9
        ///sSegpCM+2wm+jWBeLyjIQTNdihXG2ZdjQgjlYPQcnqBPdMneI5Y436BdmhD3AW8y
        ///9yEsPvnhkGCPGe2mQq5mqgaDykv/yvSEv7IstHJSP6zkWPN4B6kEKMGYAk+wFcv1
        ///sKhzxeBzbNOoXPbp9ePBZQMXLw2Zf6uFFIUSLnA2pcRnQKobrkFvU3vc9qLbzc+u
        ///mfQwyyCwzJ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string public_pgp_key {
            get {
                return ResourceManager.GetString("public_pgp_key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        internal static string test_file {
            get {
                return ResourceManager.GetString("test_file", resourceCulture);
            }
        }
    }
}
