name: CICD-Cezzi-Azure-KeyVault

on:
  pull_request:
    branches: [main]
    paths: [Cezzi.Azure/Cezzi.Azure.KeyVault/**, .github/workflows/cezzi-azure-keyvault-cicd.yaml]

  push:
    branches: [main]
    paths: [Cezzi.Azure/Cezzi.Azure.KeyVault/**, .github/workflows/cezzi-azure-keyvault-cicd.yaml]
    
  workflow_dispatch:

jobs:
  nuget-pack-and-push:
    uses: mtnvencenzo/Workflows/.github/workflows/nuget-pack-and-push.yaml@main
    with:
      working_directory: 'Cezzi.Azure/Cezzi.Azure.KeyVault'
      environment_name: 'prd'
      allow_push: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
      dotnet_version: '9.x'
      nuget_file_path: './../../Nuget.Config'
      github_nuget_feed_name: 'github-mtnvencenzo'
      github_nuget_feed_source: 'https://nuget.pkg.github.com/mtnvencenzo/index.json'
      project_path: './Cezzi.Azure.KeyVault.sln'
      test_project_path: './Cezzi.Azure.KeyVault.sln'
      publish_project_path: './src/Cezzi.Azure.KeyVault/Cezzi.Azure.KeyVault.csproj'
      artifact_name: 'cezzi-azure-keyvault-nuget'
      publish_directory_name: 'nuget'
    secrets:
      github_packages_pat_token: ${{ secrets.GH_PACKAGES_PAT_TOKEN }} 