//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cezzi.Applications.Text.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RandomSources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RandomSources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Cezzi.Applications.Text.Resources.RandomSources", typeof(RandomSources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #Alabama-AL
        ///Alexander City
        ///Andalusia
        ///Anniston
        ///Athens
        ///Atmore
        ///Auburn
        ///Bessemer
        ///Birmingham
        ///Chickasaw
        ///Clanton
        ///Cullman
        ///Decatur
        ///Demopolis
        ///Dothan
        ///Enterprise
        ///Eufaula
        ///Florence
        ///Fort Payne
        ///Gadsden
        ///Greenville
        ///Guntersville
        ///Huntsville
        ///Jasper
        ///Marion
        ///Mobile
        ///Montgomery
        ///Opelika
        ///Ozark
        ///Phenix City
        ///Prichard
        ///Scottsboro
        ///Selma
        ///Sheffield
        ///Sylacauga
        ///Talladega
        ///Troy
        ///Tuscaloosa
        ///Tuscumbia
        ///Tuskegee
        ///#Alaska-AK
        ///Anchorage
        ///Cordova
        ///Fairbanks
        ///Haines
        ///Homer
        ///Juneau
        ///Ketchikan
        ///Kodiak
        ///Kotzebue
        ///Nome
        ///Pa [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string cities {
            get {
                return ResourceManager.GetString("cities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to James
        ///Mary
        ///Robert
        ///Patricia
        ///John
        ///Jennifer
        ///Michael
        ///Linda
        ///William
        ///Elizabeth
        ///David
        ///Barbara
        ///Richard
        ///Susan
        ///Joseph
        ///Jessica
        ///Thomas
        ///Sarah
        ///Charles
        ///Karen
        ///Christopher
        ///Nancy
        ///Daniel
        ///Lisa
        ///Matthew
        ///Betty
        ///Anthony
        ///Margaret
        ///Mark
        ///Sandra
        ///Donald
        ///Ashley
        ///Steven
        ///Kimberly
        ///Paul
        ///Emily
        ///Andrew
        ///Donna
        ///Joshua
        ///Michelle
        ///Kenneth
        ///Dorothy
        ///Kevin
        ///Carol
        ///Brian
        ///Amanda
        ///George
        ///Melissa
        ///Edward
        ///Deborah
        ///Ronald
        ///Stephanie
        ///Timothy
        ///Rebecca
        ///Jason
        ///Sharon
        ///Jeffrey
        ///Laura
        ///Ryan
        ///Cynthia
        ///Jacob
        ///Kathleen
        ///Gary        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string firstnames {
            get {
                return ResourceManager.GetString("firstnames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smith
        ///Johnson
        ///Williams
        ///Brown
        ///Jones
        ///Garcia
        ///Miller
        ///Davis
        ///Rodriguez
        ///Martinez
        ///Hernandez
        ///Lopez
        ///Gonzales
        ///Wilson
        ///Anderson
        ///Thomas
        ///Taylor
        ///Moore
        ///Jackson
        ///Martin
        ///Lee
        ///Perez
        ///Thompson
        ///White
        ///Harris
        ///Sanchez
        ///Clark
        ///Ramirez
        ///Lewis
        ///Robinson
        ///Walker
        ///Young
        ///Allen
        ///King
        ///Wright
        ///Scott
        ///Torres
        ///Nguyen
        ///Hill
        ///Flores
        ///Green
        ///Adams
        ///Nelson
        ///Baker
        ///Hall
        ///Rivera
        ///Campbell
        ///Mitchell
        ///Carter
        ///Roberts
        ///Gomez
        ///Phillips
        ///Evans
        ///Turner
        ///Diaz
        ///Parker
        ///Cruz
        ///Edwards
        ///Collins
        ///Reyes
        ///Stewart
        ///Morris
        ///Morales
        ///Murphy        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string lastnames {
            get {
                return ResourceManager.GetString("lastnames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abby Park St.
        ///Adelaide Ave.
        ///Airplane Ave.
        ///Airport Ave.
        ///Airport St.
        ///Andreas Ave.
        ///Arthur St.
        ///Auerbach Ave.
        ///Auburn Ave.
        ///Barn St.
        ///Bay Ave.
        ///Beatles Ave.
        ///Belby Rd.
        ///Bus Ave.
        ///California St.
        ///Camp St.
        ///Cavour Ave.
        ///Central Cesta
        ///Central St.
        ///China Ave.
        ///Communal Square
        ///Constitution St.
        ///Copper St.
        ///Corn St.
        ///Costume St.
        ///Cresson Crescent
        ///Danish Ave.
        ///Dean Ave.
        ///Delaware Ave.
        ///Delta St.
        ///Democracy Ave.
        ///Department St.
        ///Dimitri St.
        ///Dock St.
        ///Dubnitz Rd.
        ///Eastern Cesta
        ///East Hills Ave.
        ///Easy St.
        ///Elgi [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string streetnames {
            get {
                return ResourceManager.GetString("streetnames", resourceCulture);
            }
        }
    }
}
