//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cezzi.Applications.Text.Resources{
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class UsPostalCodeRanges {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UsPostalCodeRanges() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Cezzi.Applications.Text.Resources.UsPostalCodeRanges", typeof(UsPostalCodeRanges).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 99501_99950.
        /// </summary>
        internal static string AK {
            get {
                return ResourceManager.GetString("AK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 35004_36925.
        /// </summary>
        internal static string AL {
            get {
                return ResourceManager.GetString("AL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 71601_72959.
        /// </summary>
        internal static string AR {
            get {
                return ResourceManager.GetString("AR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 75502_75502.
        /// </summary>
        internal static string AR1 {
            get {
                return ResourceManager.GetString("AR1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 85001_86556.
        /// </summary>
        internal static string AZ {
            get {
                return ResourceManager.GetString("AZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 90001_96162.
        /// </summary>
        internal static string CA {
            get {
                return ResourceManager.GetString("CA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 80001_81658.
        /// </summary>
        internal static string CO {
            get {
                return ResourceManager.GetString("CO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6001_6389.
        /// </summary>
        internal static string CT {
            get {
                return ResourceManager.GetString("CT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6401_6928.
        /// </summary>
        internal static string CT1 {
            get {
                return ResourceManager.GetString("CT1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 20001_20039.
        /// </summary>
        internal static string DC {
            get {
                return ResourceManager.GetString("DC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 20042_20599.
        /// </summary>
        internal static string DC1 {
            get {
                return ResourceManager.GetString("DC1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 20799_20799.
        /// </summary>
        internal static string DC2 {
            get {
                return ResourceManager.GetString("DC2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 19701_19980.
        /// </summary>
        internal static string DE {
            get {
                return ResourceManager.GetString("DE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 32004_34997.
        /// </summary>
        internal static string FL {
            get {
                return ResourceManager.GetString("FL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 30001_31999.
        /// </summary>
        internal static string GA {
            get {
                return ResourceManager.GetString("GA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 39901_39901.
        /// </summary>
        internal static string GA1 {
            get {
                return ResourceManager.GetString("GA1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 96701_96898.
        /// </summary>
        internal static string HI {
            get {
                return ResourceManager.GetString("HI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 50001_52809.
        /// </summary>
        internal static string IA {
            get {
                return ResourceManager.GetString("IA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 68119_68120.
        /// </summary>
        internal static string IA1 {
            get {
                return ResourceManager.GetString("IA1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 83201_83876.
        /// </summary>
        internal static string ID {
            get {
                return ResourceManager.GetString("ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 60001_62999.
        /// </summary>
        internal static string IL {
            get {
                return ResourceManager.GetString("IL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 46001_47997.
        /// </summary>
        internal static string IN {
            get {
                return ResourceManager.GetString("IN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 66002_67954.
        /// </summary>
        internal static string KS {
            get {
                return ResourceManager.GetString("KS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 40003_42788.
        /// </summary>
        internal static string KY {
            get {
                return ResourceManager.GetString("KY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 70001_71232.
        /// </summary>
        internal static string LA {
            get {
                return ResourceManager.GetString("LA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 71234_71497.
        /// </summary>
        internal static string LA1 {
            get {
                return ResourceManager.GetString("LA1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1001_2791.
        /// </summary>
        internal static string MA {
            get {
                return ResourceManager.GetString("MA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5501_5544.
        /// </summary>
        internal static string MA1 {
            get {
                return ResourceManager.GetString("MA1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 20331_20331.
        /// </summary>
        internal static string MD {
            get {
                return ResourceManager.GetString("MD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 20335_20797.
        /// </summary>
        internal static string MD1 {
            get {
                return ResourceManager.GetString("MD1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 20812_21930.
        /// </summary>
        internal static string MD2 {
            get {
                return ResourceManager.GetString("MD2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3901_4992.
        /// </summary>
        internal static string ME {
            get {
                return ResourceManager.GetString("ME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 48001_49971.
        /// </summary>
        internal static string MI {
            get {
                return ResourceManager.GetString("MI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 55001_56763.
        /// </summary>
        internal static string MN {
            get {
                return ResourceManager.GetString("MN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 63001_65899.
        /// </summary>
        internal static string MO {
            get {
                return ResourceManager.GetString("MO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 38601_39776.
        /// </summary>
        internal static string MS {
            get {
                return ResourceManager.GetString("MS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 71233_71233.
        /// </summary>
        internal static string MS1 {
            get {
                return ResourceManager.GetString("MS1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 59001_59937.
        /// </summary>
        internal static string MT {
            get {
                return ResourceManager.GetString("MT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 27006_28909.
        /// </summary>
        internal static string NC {
            get {
                return ResourceManager.GetString("NC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 58001_58856.
        /// </summary>
        internal static string ND {
            get {
                return ResourceManager.GetString("ND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 68001_68118.
        /// </summary>
        internal static string NE {
            get {
                return ResourceManager.GetString("NE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 68122_69367.
        /// </summary>
        internal static string NE1 {
            get {
                return ResourceManager.GetString("NE1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3031_3897.
        /// </summary>
        internal static string NH {
            get {
                return ResourceManager.GetString("NH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7001_8989.
        /// </summary>
        internal static string NJ {
            get {
                return ResourceManager.GetString("NJ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 87001_88441.
        /// </summary>
        internal static string NM {
            get {
                return ResourceManager.GetString("NM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 88901_89883.
        /// </summary>
        internal static string NV {
            get {
                return ResourceManager.GetString("NV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6390_6390.
        /// </summary>
        internal static string NY {
            get {
                return ResourceManager.GetString("NY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10001_14975.
        /// </summary>
        internal static string NY1 {
            get {
                return ResourceManager.GetString("NY1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 43001_45999.
        /// </summary>
        internal static string OH {
            get {
                return ResourceManager.GetString("OH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 73001_73199.
        /// </summary>
        internal static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 73401_74966.
        /// </summary>
        internal static string OK1 {
            get {
                return ResourceManager.GetString("OK1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 97001_97920.
        /// </summary>
        internal static string OR {
            get {
                return ResourceManager.GetString("OR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 15001_19640.
        /// </summary>
        internal static string PA {
            get {
                return ResourceManager.GetString("PA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2801_2940.
        /// </summary>
        internal static string RI {
            get {
                return ResourceManager.GetString("RI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 29001_29948.
        /// </summary>
        internal static string SC {
            get {
                return ResourceManager.GetString("SC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 57001_57799.
        /// </summary>
        internal static string SD {
            get {
                return ResourceManager.GetString("SD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 37010_38589.
        /// </summary>
        internal static string TN {
            get {
                return ResourceManager.GetString("TN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 73301_73301.
        /// </summary>
        internal static string TX {
            get {
                return ResourceManager.GetString("TX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 75001_75501.
        /// </summary>
        internal static string TX1 {
            get {
                return ResourceManager.GetString("TX1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 75503_79999.
        /// </summary>
        internal static string TX2 {
            get {
                return ResourceManager.GetString("TX2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 88510_88589.
        /// </summary>
        internal static string TX3 {
            get {
                return ResourceManager.GetString("TX3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 84001_84784.
        /// </summary>
        internal static string UT {
            get {
                return ResourceManager.GetString("UT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 20040_20041.
        /// </summary>
        internal static string VA {
            get {
                return ResourceManager.GetString("VA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 20040_20167.
        /// </summary>
        internal static string VA1 {
            get {
                return ResourceManager.GetString("VA1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 20042_20042.
        /// </summary>
        internal static string VA2 {
            get {
                return ResourceManager.GetString("VA2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 22001_24658.
        /// </summary>
        internal static string VA3 {
            get {
                return ResourceManager.GetString("VA3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5001_5495.
        /// </summary>
        internal static string VT {
            get {
                return ResourceManager.GetString("VT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5601_5907.
        /// </summary>
        internal static string VT1 {
            get {
                return ResourceManager.GetString("VT1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 98001_99403.
        /// </summary>
        internal static string WA {
            get {
                return ResourceManager.GetString("WA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 53001_54990.
        /// </summary>
        internal static string WI {
            get {
                return ResourceManager.GetString("WI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 24701_26886.
        /// </summary>
        internal static string WV {
            get {
                return ResourceManager.GetString("WV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 82001_83128.
        /// </summary>
        internal static string WY {
            get {
                return ResourceManager.GetString("WY", resourceCulture);
            }
        }
    }
}
